export const ACTION_AUTH_REGISTER = 'ACTION_AUTH_REGISTER';
export const ACTION_AUTH_LOGGED_IN = 'ACTION_AUTH_LOGGED_IN';

export const ACTION_USER_GET_USER = 'ACTION_USER_GET_USER';
export const ACTION_USER_OPEN_CHAT_BOX = 'ACTION_USER_OPEN_CHAT_BOX';
export const ACTION_USER_SHOW_HOT_TOAST = 'ACTION_USER_SHOW_HOT_TOAST';
export const ACTION_USER_SNACKBAR = 'ACTION_USER_SNACKBAR';
export const ACTION_USER_BACKDROP = 'ACTION_USER_BACKDROP';

export const ACTION_FOOD_GET_TYPE_CHOSEN = 'ACTION_FOOD_GET_TYPE_CHOSEN';
export const ACTION_FOOD_GET_ALL_FOODS = 'ACTION_FOOD_GET_ALL_FOODS';
export const ACTION_FOOD_GET_ALL_TYPE_FOODS = 'ACTION_FOOD_GET_ALL_TYPE_FOODS';
export const ACTION_FOOD_GET_ALL_FOODS_BY_NAME = 'ACTION_FOOD_GET_ALL_FOODS_BY_NAME';

export const ACTION_ORDER_GET_ORDER = 'ACTION_ORDER_GET_ORDER';
export const ACTION_ORDER_ADD_FOODS = 'ACTION_ORDER_ADD_FOODS';
export const ACTION_ORDER_EDIT_FOODS = 'ACTION_ORDER_EDIT_FOODS';
export const ACTION_ORDER_DELETE_FOODS = 'ACTION_ORDER_DELETE_FOODS';
export const ACTION_ORDER_SET_FOODS = 'ACTION_ORDER_SET_FOODS';
export const ACTION_ORDER_MODAL_INFORMATION_FOOD = 'ACTION_ORDER_MODAL_INFORMATION_FOOD';
export const ACTION_ORDER_GET_ALL_ORDERS = 'ACTION_ORDER_GET_ALL_ORDERS';
export const ACTION_ORDER_GET_ALL_BOOKS = 'ACTION_ORDER_GET_ALL_BOOKS';

export const ACTION_AREA_GET_ALL_AREAS = 'ACTION_AREA_GET_ALL_AREAS';

export const ACTION_SOCKET_GET_SOCKET = 'ACTION_SOCKET_GET_SOCKET';
export const ACTION_SOCKET_ME = 'ACTION_SOCKET_ME';
export const ACTION_SOCKET_BROADCAST_SOCKET = 'ACTION_SOCKET_BROADCAST_SOCKET';
