export const ACTION_AUTH_REGISTER = 'ACTION_AUTH_REGISTER';
export const ACTION_AUTH_LOGGED_IN = 'ACTION_AUTH_LOGGED_IN';

export const ACTION_USER_GET_USER = 'ACTION_USER_GET_USER';
export const ACTION_USER_OPEN_CHAT_BOX = 'ACTION_USER_OPEN_CHAT_BOX';
export const ACTION_USER_SHOW_HOT_TOAST = 'ACTION_USER_SHOW_HOT_TOAST';

export const ACTION_FOOD_GET_TYPE_CHOSEN = 'ACTION_FOOD_GET_TYPE_CHOSEN';
export const ACTION_FOOD_GET_ALL_FOODS = 'ACTION_FOOD_GET_ALL_FOODS';
export const ACTION_FOOD_GET_ALL_TYPE_FOODS = 'ACTION_FOOD_GET_ALL_TYPE_FOODS';

export const ACTION_ORDER_GET_ORDER = 'ACTION_ORDER_GET_ORDER';
export const ACTION_ORDER_ADD_FOODS = 'ACTION_ORDER_ADD_FOODS';
export const ACTION_ORDER_EDIT_FOODS = 'ACTION_ORDER_EDIT_FOODS';
export const ACTION_ORDER_DELETE_FOODS = 'ACTION_ORDER_DELETE_FOODS';
export const ACTION_ORDER_MODAL_INFORMATION_FOOD = 'ACTION_ORDER_MODAL_INFORMATION_FOOD';
